config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/users/edit', to: 'devise/registrations#edit'
  get '/users/index', to: 'users#index'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :microposts, only: [:create, :destroy, :edit, :update]
  
  resources :microposts do
    resources :likes, only: [:create, :destroy]
    resources :comments #, only: [:create, :destroy, :edit, :update]
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :micropost
  belongs_to :user
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy, :update]
  before_action :is_admin, only: :destroy

  def index
    @micropost = Micropost.find(params[:micropost_id])
    @comments = @micropost.comments.paginate(page: params[:page])
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.micropost_id = params[:micropost_id]
    if @comment.save
      flash[:success] = "Comment created!"
      redirect_back fallback_location: root_path
    else
      flash[:alert] = "Comment not created"
      redirect_back fallback_location: root_path
    end
  end

  def edit
    @comment = Comment.find_by(id: params[:id])
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    if @comment.update(update_comment_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id]) # current_user.comments
    @comment.destroy
    flash[:success] = "Comment deleted"
    redirect_to request.referrer || root_url # previous URL or root URl
  end
 
  private

    def comment_params
      params.permit(:content)
      # params.require(:comment).permit(:content) #doesn't work, why!??????
    end
    
    def update_comment_params # ........
      params.require(:comment).permit(:content)
    end

    def correct_user
      @comment = current_user.comments.find_by(id: params[:id])
      redirect_to root_url if @comment.nil?
    end

    def is_admin
      current_user.admin = true
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li>
  <span class="user"><%= link_to comment.user.name, comment.user %>: </span>
    <span class="content">
      <%= comment.content %>
    </span>
  </span> 
  <% if current_user.id == comment.user_id || current_user.admin == true %>
    <%= link_to "delete", micropost_comment_path(comment.micropost_id, comment.id), method: :delete  %>
  <% end %>
  <% if current_user.id == comment.user_id %>
    <%= link_to "| edit", edit_micropost_comment_path(comment.micropost_id, comment.id) %>
  <% end %>

</li>

app/views/comments/_comment_form.html.erb
<%= form_with(model: @comment, url: micropost_comments_path, method: :post) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new comment..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/comments/edit.html.erb
<%= form_with(model: @comment, url: micropost_comment_path(@comment.micropost_id, @comment.id), method: :patch) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: @comment.content %>
  </div>
  <%= f.submit "Update", class: "btn btn-primary" %>
<% end %>

app/views/comments/index.html.erb
<h1> Comment to: </h1>
<h2> <%= render html:  @micropost.content  %> </h2>

<%= render 'comments/comment_form' %>
<h1>All comments</h1>
<%= will_paginate %>
  <ul class="comments">
    <%= render @micropost.comments %>
  </ul>
<%= will_paginate %>