config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/users/edit', to: 'devise/registrations#edit'
  get '/users/index', to: 'users#index'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :microposts, only: [:create, :destroy, :edit, :update]
  
  resources :microposts do
    resources :likes, only: [:create, :destroy]
    resources :comments #, only: [:create, :destroy, :edit, :update]
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy, :update]
  before_action :is_admin, only: :destroy
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'static_pages/home'
    end
  end

  def edit
    @micropost = Micropost.find_by(id: params[:id])
    render 'edit'
  end

  def update
    @micropost = Micropost.find_by(id: params[:id])
    if @micropost.update(micropost_params)
    redirect_to root_url
    else 
      render 'edit'
    end
  end

  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    # in prev string we find the concrete post, wich we want to delete
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url # previous URL or root URl
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :image)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end

    def is_admin
      current_user.admin = true
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items,
                    params: {controller: :static_pages, action: :home} %> <!-- work without params: {} , why? -->
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <span class="user"><%= link_to micropost.user.name, micropost.user %> :</span>
  <span class="content">
      <%= micropost.content %>
      <%= image_tag micropost.image_url if micropost.image %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user || current_user.admin == true %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?"} %>
    <% end %>
    <% if current_user == micropost.user %>
      <%= link_to "| edit", edit_micropost_path(micropost) %>
    <% end %>
    <%= link_to "| comments", micropost_comments_path(micropost) %>

    <p><%= micropost.likes.count %> <%= (micropost.likes.count) == 1 ? 'Like' : 'Likes'%>
    
    <% pre_like = micropost.likes.find { |like| like.user_id == current_user.id} %>
    <% if pre_like %>
      <%= button_to 'Unlike', micropost_like_path(micropost, pre_like), method: :delete %>
    <% else %>
      <%= button_to 'Like', micropost_likes_path(micropost), method: :post %>
    <% end %>
    
  </span>
</li>

app/views/microposts/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  
  <div class="field">
    <%= image_tag f.object.image_url if f.object.cached_image_data %>
    <%= f.hidden_field :image, value: f.object.cached_image_data %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/microposts/edit.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: @micropost.content %>
  </div>
  <p>
    Uploaded images below:
  </p>
  <%= image_tag @micropost.image_url if @micropost.image %>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  
  <%= f.submit "update", class: "btn btn-primary" %>
<% end %>