config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/users/edit', to: 'devise/registrations#edit'
  get '/users/index', to: 'users#index'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :microposts, only: [:create, :destroy, :edit, :update]
  
  resources :microposts do
    resources :likes, only: [:create, :destroy]
    resources :comments #, only: [:create, :destroy, :edit, :update]
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <%= link_to image_tag("plant.jpg", alt: "Plant", width: "200"), "https://github.com/heartcombo/devise" %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Blog", root_path, id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                              data-toggle="collapse"
                              data-target="#bs-example-navbar-collapse-1"
                              aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse"
          id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>   <!-- here is the link 'root_path' -->
        <li><%= link_to "Help", help_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Users", users_index_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Settings", edit_user_registration_path, method: :get %></li>
        <% else %> 
        <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice%></p>
    <p class="alert"><%=alert%></p>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
  
</html>